.github: Attempt to fix ubuntu 20.04 clang build
clang-11 only seems to pull in libstdc++-9-dev, not libstdc++-10-dev.
The former does not seem to have <span> causing the following
compilation error:

	In file included from ../vendor/adb/client/file_sync_client.cpp:46:
	../vendor/adb/compression_utils.h:21:10: fatal error: 'span' file not found
	#include <span>