cmake: Disable e2fsdroid in macOS
This is disabled due to following compiler error.

core/libcutils/include/private/fs_config.h:26:10: fatal error: 'linux/capability.h' file not found
include <linux/capability.h>
         ^~~~~~~~~~~~~~~~~~~~