CMake: Fix linking with private abseil-cpp libraries
This fixes the following linking errors

vendor/libliblpdump.a(dynamic_partitions_device_info.pb.cc.o):
undefined reference to symbol '_ZN4absl12lts_2023012512log_internal21CheckOpMessageBuilder7ForVar2Ev'
/usr/lib/libabsl_log_internal_check_op.so.2301.0.0: error adding symbols: DSO missing from command line

The find_package was called twice because protobuf-config.cmake file
was not present in versions older than 22.0. Also the Config mode is
required to get the private abseil-cpp libraries.